/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  locked: () => import("@/views/_builtin/locked/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "base64-converter": () => import("@/views/base64-converter/index.vue"),
  "btc-course-flow": () => import("@/views/btc-course-flow/index.vue"),
  "effects-generator": () => import("@/views/effects-generator/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "image-compressor": () => import("@/views/image-compressor/index.vue"),
  "image-matting": () => import("@/views/image-matting/index.vue"),
  "material-studio": () => import("@/views/material-studio/index.vue"),
  "qrcode-generator": () => import("@/views/qrcode-generator/index.vue"),
  "quick-links": () => import("@/views/quick-links/index.vue"),
  "role-manager": () => import("@/views/role-manager/index.vue"),
  "sb3-compressor": () => import("@/views/sb3-compressor/index.vue"),
  "sb3-studio": () => import("@/views/sb3-studio/index.vue"),
  "timestamp-converter": () => import("@/views/timestamp-converter/index.vue"),
  "tts-studio": () => import("@/views/tts-studio/index.vue"),
  "user-manager": () => import("@/views/user-manager/index.vue"),
  "video-frame-extractor": () => import("@/views/video-frame-extractor/index.vue"),
};
